# -*- coding: utf-8 -*-
"""Generate tables/ablation.tex: the trial with one element removed or replaced.

Real data: combinations of 84 significant after pooled Holm correction under
each variant's comparison.  Synthetic: false-positive rate over 200
populations with no individual signal.

Inputs: <ANALYSIS>/gains.json (no user / population / group rows),
<ANALYSIS>/identity.json (the full trial and the updated-profile variant),
<VALIDATION>/matcher_hierarchy.json (nearest-neighbour rule) and
<VALIDATION>/reference_nulls.json (synthetic columns).

    python -m attribution_trials.tables.ablation
Output: <TABLES>/ablation.tex
"""

import json

from attribution_trials import paths

NA = r'\textcolor{ATtablemuted}{n/a}'  # not applicable or not run
FINE = 'group, fine'  # groups finer than the matching cells


def main():
    gains = json.loads((paths.ANALYSIS / 'gains.json').read_text())
    identity = json.loads((paths.ANALYSIS / 'identity.json').read_text())
    matcher = json.loads((paths.VALIDATION / 'matcher_hierarchy.json').read_text())['rows']
    nulls = json.loads((paths.VALIDATION / 'reference_nulls.json').read_text())['results']
    SR = gains['rows']

    holm_keys = [c['key'] for c in identity['cells'] if c['identity']['holm_pooled']]
    DRIFT = [k for k in nulls if k.startswith('drift')]
    nn_kept = sum(1 for r in matcher if r.get('certified_identity') and r['nn']['high'] < 0)
    nn_of = sum(1 for r in matcher if r.get('certified_identity'))
    assert nn_of == len(holm_keys), (nn_of, len(holm_keys))

    def rate(null, contrast):
        node = nulls[null]
        return f"{node[contrast]['favourable_rate']:.3f}" if contrast in node else NA

    def worst_drift(contrast):
        vals = [nulls[k][contrast]['favourable_rate'] for k in DRIFT if contrast in nulls[k]]
        return f"{max(vals):.3f}" if vals else NA

    def synth(contrast):
        return f"{rate('population', contrast)} & {worst_drift(contrast)} & {rate('group, matched', contrast)} & {rate(FINE, contrast)}"

    A = [
        ('AT', 'AT: target vs imposter'),
        ('none', 'target vs no user'),
        ('pop', 'target vs population'),
        ('grp', 'target vs group'),
        ('live', 'updated information vs imposter'),
        ('nn', 'AT, nearest-neighbour imposter'),
    ]
    holm = {k: SR[k]['holm_pooled']['target'] for k in ('dtot', 'dpop', 'dgrp')}
    live_passes = identity['counts']['registered']['pooled-84']['holm_pooled_survivors']

    lines = [
        r"% Generated by attribution_trials.tables.ablation.",
        r"\begin{table}[t]",
        r"\definecolor{ATtablemuted}{HTML}{9AA1A8}",
        r"\caption{\textbf{Removing or replacing one element of the trial at a time.} \emph{Real data}: combinations "
        r"of 84 significant against the variant's comparison after Holm correction, the one gain the variant changes "
        r"(Section~\ref{sec:stats}); no combination passes the full rule. \emph{Synthetic}: false-positive rate over 200 populations with no "
        r"individual signal, so anything above the nominal $5\%$ is a failure: users drawn from one shared rate; "
        r"that rate drifting across the training boundary (worst of three magnitudes); users differing only by "
        r"the group the rule matches on; and groups finer than the matching cells. "
        + rf"$^\ast$Of the {nn_of} combinations significant after correction under the registered rule, those still significant under the nearest-neighbor rule, "
        r"which was recomputed on nine combinations. n/a: not applicable or not run. Settings in Appendix~\ref{app:stress}.}",
        r"\label{tab:ablation}",
        r"\centering",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}p{5.0cm}ccccc@{}}",
        r"\toprule",
        r"& Real data & \multicolumn{4}{c}{Synthetic population, no individual signal} \\",
        r"\cmidrule(lr){2-2}\cmidrule(l){3-6}",
        r"Variant & \shortstack{Significant after\\correction / 84} & Shared rate & \; + drift & \; + group & \; + finer group \\",
        r"\midrule",
        f"\\textbf{{Attribution Trials}} (full) & {len(holm_keys)} & {synth(A[0][1])} \\\\",
        r"\midrule",
        f"Compared with: no user information & {holm['dtot']} & {synth(A[1][1])} \\\\",
        f"Compared with: generic population & {holm['dpop']} & {synth(A[2][1])} \\\\",
        f"Compared with: matched group & {holm['dgrp']} & {synth(A[3][1])} \\\\",
        r"\midrule",
        f"Information updated with held-out rows & {live_passes} & {synth(A[4][1])} \\\\",
        r"\midrule",
        f"Matching rule: five-feature nearest neighbor & {nn_kept} of {nn_of}$^\\ast$ & {synth(A[5][1])} \\\\",
        r"\bottomrule",
        r"\end{tabular*}",
        r"\end{table}",
    ]
    out = paths.ensure(paths.TABLES) / 'ablation.tex'
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}")


if __name__ == '__main__':
    main()
