"""Appendix table (tab:combinations): which method runs on which behavior channel, giving the 84 combinations.

Reads the 84 keys of paths.ANALYSIS / "gains.json".  Writes paths.TABLES / "combinations.tex".
Run:  python -m attribution_trials.tables.combinations
"""

import json
from collections import Counter, defaultdict

from attribution_trials import paths

SRC = paths.ANALYSIS / "gains.json"
OUT = paths.TABLES / "combinations.tex"

ROWS = [  # (display label, family code, model code or None)
    ("static embedding", "static-embedding", None),
    ("recurrent embedding", "evolving-latent", None),
    ("structured memory", "structured-memory", None),
    ("user-profile LoRA 1.7B", "sft-lora", "1.7b"),
    ("user-profile LoRA 8B", "sft-lora", "8b"),
    ("frozen prompt 1.7B", "persona-frozen", "1.7b"),
    ("frozen prompt 8B", "persona-frozen", "8b"),
    ("frozen prompt 30B-A3B", "strong-open", "30b"),
    ("Osim 4B", "trained-sim", "osim-4b"),
    ("Osim 4B-mid", "trained-sim", "osim-4b-mid"),
    ("Osim 8B", "trained-sim", "osim-8b"),
    ("Osim 8B-mid", "trained-sim", "osim-8b-mid"),
    ("CoSER-8B", "sim2real-trio", "coser-8b"),
    ("HumanLike-7B", "sim2real-trio", "humanlike-7b"),
]
COLS = ["chess|move", "chess|timing", "KT|response", "KT|timing", "OPeRA|action", "OPeRA|timing"]


def main():
    cells = json.loads(SRC.read_text())["cells"]
    count = defaultdict(Counter)
    for c in cells:
        parts = c["key"].split("|")
        fam = parts[0]
        if c["dataset"] == "OPeRA":
            model, channel = parts[3], "OPeRA|" + parts[1]
        else:
            model = parts[1].split("(")[1].rstrip(")") if "(" in parts[1] else None
            channel = ("chess|" if "chess" in parts[1] else "KT|") + (
                "timing"
                if parts[2] == "timing"
                else ("move" if "chess" in parts[1] else "response")
            )
        count[(fam, model)][channel] += 1
    total = 0
    lines = [
        "% AUTO-GENERATED by attribution_trials.tables.combinations; do not edit by hand.",
        r"\begin{table}[htbp]",
        r"\caption{\textbf{The 84 combinations.} Each cell is the number of combinations a method contributes on one behavior channel: "
        r"one per channel, or three on OPeRA, where the profile comes in a static, a dynamic, and a combined configuration; "
        r"`mid' marks midtrained Osim checkpoints. Static embedding contributes a second KT response combination from a response-only model.}",
        r"\label{tab:combinations}",
        r"\centering",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{5pt}",
        r"\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lcc@{\hspace{10pt}}cc@{\hspace{10pt}}cc@{}}",
        r"\toprule",
        r"& \multicolumn{2}{c}{Chess} & \multicolumn{2}{c}{KT} & \multicolumn{2}{c}{OPeRA} \\",
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(l){6-7}",
        r"Method & move & timing & response & timing & action & timing \\",
        r"\midrule",
    ]
    for label, fam, model in ROWS:
        ctr = count[(fam, model)]
        row = []
        for col in COLS:
            n = ctr.get(col, 0)
            total += n
            row.append("" if n == 0 else (r"\yesmark" if n == 1 else str(n)))
        lines.append(label + " & " + " & ".join(row) + r" \\")
    lines += [
        r"\midrule",
        r"Combinations & \multicolumn{2}{c}{8} & \multicolumn{2}{c}{10} & \multicolumn{2}{c}{66} \\",
        r"\bottomrule",
        r"\end{tabular*}",
        r"\end{table}",
        "",
    ]
    assert total == 84, total
    # the response-only static-embedding model shows as "2" in KT response; the caption explains it
    paths.ensure(OUT.parent)
    OUT.write_text("\n".join(lines))
    print("wrote", OUT, "total", total)


if __name__ == "__main__":
    main()
