# -*- coding: utf-8 -*-
"""Generate tables/comparison_upstream.tex: evaluation methods on the 84 audit
combinations, each recomputed with the matched imposter's information in place
of the target's.

Inputs: <ANALYSIS>/gains.json (profile-versus-none row, perplexity row,
Attribution Trials counts and the pooled-Holm key set),
<COMPARISON>/comparison_rows.json (random profile, accuracy, total variation,
population JS rows, and the Olmo block) and <COMPARISON>/coverage_table.json
(the number of method populations in the population-realism row).

    python -m attribution_trials.tables.comparison_upstream
Output: <TABLES>/comparison_upstream.tex
"""

import json

import numpy as np

from attribution_trials import paths

NA = r'\textcolor{ATtablemuted}{n/a}'  # not computable for that method on that data


def frac(fav, d, N):
    return f"{fav[d]}/{N[d]}"


def counts_row(node, N):
    return [frac(node['favourable'], d, N) for d in ('chess', 'KT', 'OPeRA')] + [
        f"{node['favourable']['all']}/84"
    ]


def method_counts(node):
    """chess / KT / OPeRA / all over the combinations the row can be computed on; n/a where none."""
    return [
        f"{node['favourable'][d]}/{node['n'][d]}" if node['n'][d] else NA
        for d in ('chess', 'KT', 'OPeRA')
    ] + [f"{node['favourable']['all']}/{node['n']['all']}"]


def method_still(node):
    return f"{node['still_favourable']['all']}/{node['favourable']['all']}"


def method_kept(node):
    return f"{node['gain_kept_pct']['median']:.1f}\\%"


def main() -> None:
    gains = json.loads((paths.ANALYSIS / 'gains.json').read_text())
    coverage = json.loads((paths.COMPARISON / 'coverage_table.json').read_text())
    methods = json.loads((paths.COMPARISON / 'comparison_rows.json').read_text())

    N = gains['n_cells']  # per dataset: chess, KT, OPeRA
    SR = gains['rows']
    M = methods['rows']

    holm_keys = SR['dind']['holm_pooled']['target_keys']
    holm_by_ds = {
        d: sum(1 for k in holm_keys if ('chess' in k if d == 'chess' else 'kt' in k))
        for d in ('chess', 'KT')
    }
    holm_by_ds['OPeRA'] = len(holm_keys) - holm_by_ds['chess'] - holm_by_ds['KT']
    n_populations = sum(1 for r in coverage if '::' not in r['cell'])
    ppl_kept = float(np.median([100 / c['ppl_ratio'] for c in gains['cells']]))

    tot, ind = SR['dtot'], SR['dind']
    rows = [
        ("Perplexity of real behavior", "userlm,osim", [NA] * 4, NA, f"{ppl_kept:.1f}\\%"),
        (
            "Profile versus no profile",
            "realusersim,userlm",
            counts_row(tot, N),
            rf"{tot['still_favourable']['all']}/{tot['favourable']['all']}",
            f"{tot['gain_kept_pct']['median']:.1f}\\%",
        ),
        (
            "Random unrelated profile",
            "behaviorbench",
            method_counts(M['random_profile']),
            method_still(M['random_profile']),
            method_kept(M['random_profile']),
        ),
        (
            "Next-decision accuracy",
            "behaviorbench,personamem",
            method_counts(M['accuracy']),
            method_still(M['accuracy']),
            method_kept(M['accuracy']),
        ),
        (
            "Group-level total variation",
            "simbench,meister",
            method_counts(M['total_variation']),
            method_still(M['total_variation']),
            method_kept(M['total_variation']),
        ),
        (
            "Population realism",
            "distgap,simevalir",
            [NA] * 3 + [f"0/{n_populations}"],
            NA,
            f"{M['population']['js_kept_pct']['median']:.1f}\\%",
        ),
    ]

    lines = [
        r"% AUTO-GENERATED by attribution_trials.tables.comparison_upstream; do not edit by hand.",
        r"\begin{table}[t]",
        r"\definecolor{ATtablemuted}{HTML}{9AA1A8}",
        r"\caption{\textbf{Existing benchmarks barely change their score when the simulator is "
        r"given the matched imposter's information.} "
        r"Left: how many of the 84 combinations the evaluation "
        r"judges significant, over the combinations it can be computed on (52 for accuracy and total "
        r"variation, 5 for the random-profile control; n/a where none). Right: the same score recomputed "
        r"with $\pimposter$ in place of $\ptarget$, as the combinations still significant and the score kept "
        r"(Section~\ref{sec:comparison}); Attribution Trials keeps $0\%$ by construction. In parentheses: "
        r"after Holm-Bonferroni correction.}",
        r"\label{tab:comparison-upstream}",
        r"\centering",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}p{4.1cm}cccccc@{}}",
        r"\toprule",
        r"& \multicolumn{4}{c}{Combinations judged significant} & \multicolumn{2}{c}{With $\pimposter$ for $\ptarget$} \\",
        r"\cmidrule(lr){2-5}\cmidrule(l){6-7}",
        r"Evaluation method & Chess & KT & OPeRA & All & Still sig. & Score kept \\",
        r"\midrule",
    ]
    for name, cites, cols, still, kept in rows:
        head = (
            f"{name}\\newline\\citep{{{cites}}}" if cites else name
        )  # citation on its own line under the method
        lines.append(f"{head} & " + " & ".join(cols) + f" & {still} & {kept} \\\\")
    lines += [
        r"\midrule",
        r"\textbf{Attribution Trials} (ours) & "
        + " & ".join(
            [f"{ind['favourable'][d]}/{N[d]} ({holm_by_ds[d]})" for d in ('chess', 'KT', 'OPeRA')]
            + [f"{ind['favourable']['all']}/84 ({len(holm_keys)})"]
        )
        + f" & {ind['still_favourable']['all']}/{ind['favourable']['all']} & $0.0\\%$ \\\\",
        r"\bottomrule",
        r"\end{tabular*}",
        r"\end{table}",
    ]
    out = paths.ensure(paths.TABLES) / 'comparison_upstream.tex'
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}")

    # Olmo-3.1-32B (outside the 84): the counts behind the appendix paragraph.
    OL = methods['olmo']
    olmo_fav = {
        k: sum(v['target'][k]['high'] < 0 for v in OL.values())
        for k in ('dtot', 'dpop', 'dgrp', 'dind')
    }
    olmo_adv_tot = sum(v['target']['dtot']['low'] > 0 for v in OL.values())
    olmo_fav_acc = sum(v['accuracy']['A4f'] > v['accuracy']['A0'] for v in OL.values())
    _tvd_gain = [
        (v['mean_tvd']['A0'] - v['mean_tvd']['A4f'], v['mean_tvd']['A0'] - v['mean_tvd']['A3'])
        for v in OL.values()
    ]
    olmo_fav_tvd = sum(g > 0 for g, _ in _tvd_gain)
    olmo_still_tvd = sum(g > 0 and s > 0 for g, s in _tvd_gain)
    print(
        f"Olmo ({len(OL)} configurations): gains favouring the target {olmo_fav}; "
        f"profile-versus-none adverse on {olmo_adv_tot}; accuracy favours the profile on {olmo_fav_acc}; "
        f"total variation favours it on {olmo_fav_tvd}, still under the imposter on {olmo_still_tvd}"
    )


if __name__ == '__main__':
    main()
