"""Appendix table: the LLM judge's score under the target's and under the matched imposter's profile, per simulator.

Reads ``paths.WILDCHAT / "judge_readout.json"``; writes ``paths.TABLES / "judge_stranger.tex"``.

  python -m attribution_trials.tables.judge_stranger
"""

import json

from attribution_trials import paths

SRC = paths.WILDCHAT / "judge_readout.json"
NAMES = {
    "1.7b": "Qwen3-1.7B",
    "8b": "Qwen3-8B",
    "dense": "Qwen3-32B (dense)",
    "humanlike": "HumanLike-7B",
    "coser": "CoSER-8B",
    "osim": "Osim-8B",
    "humanlm": "HumanLM-opinion",
}
FID, ALI = "judged fidelity (RealUserSim PT3 index)", "judged alignment (HumanLM key points)"


def main():
    g = json.loads(SRC.read_text())
    assert g["coverage"]["n_missing"] == 0 and g["coverage"]["n_failed_in_judge"] == 0
    lines = [
        "% AUTO-GENERATED by attribution_trials.tables.judge_stranger; do not edit by hand.",
        r"\begin{table}[htbp]",
        r"\caption{\textbf{An LLM judge does register the matched imposter's profile.} Mean judge score of the generated turn against the real one "
        r"("
        + g["model"]
        + r", blind to which profile was used; one sample per turn, 1{,}427 turns of 236 users) under the target's and under the "
        r"matched imposter's profile, with the paired-user 95\% interval of the difference and the share of the target score kept. "
        r"Fidelity is the mean of five binary matches (persona, style, competency, interaction flow, pacing); alignment is the share of the real turn's key points covered.}",
        r"\label{tab:judge-stranger}",
        r"\centering",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrr@{\hspace{12pt}}rrr@{}}",
        r"\toprule",
        r"& \multicolumn{3}{c}{Judged fidelity} & \multicolumn{3}{c}{Judged alignment} \\",
        r"\cmidrule(lr){2-4}\cmidrule(l){5-7}",
        r"Simulator & target & imposter & kept & target & imposter & kept \\",
        r"\midrule",
    ]
    for key, name in NAMES.items():
        cells = []
        for metric in (FID, ALI):
            s = g["stranger"][metric][key]
            cells += [
                f"{s['target_A4']:.3f}",
                f"{s['stranger_A3']:.3f}",
                f"{100 * s['share_kept']:.0f}\\%",
            ]
        lines.append(name + " & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular*}", r"\end{table}", ""]
    out = paths.ensure(paths.TABLES) / "judge_stranger.tex"
    out.write_text("\n".join(lines))
    print("wrote", out)


if __name__ == "__main__":
    main()
