"""Appendix longtable (tab:master-ladder): Delta_indiv with its 95% interval for all 84 combinations.

Reads paths.ANALYSIS / "master_ladder.csv".  Writes paths.TABLES / "appendix_master_ladder.tex".
Run:  python -m attribution_trials.tables.master_ladder
"""

import csv

from attribution_trials import paths

SRC = paths.ANALYSIS / "master_ladder.csv"
OUT = paths.TABLES / "appendix_master_ladder.tex"

PANEL_ORDER = ["full-tier", "opera-gpu", "sim2real-trio", "osim-panel"]
PANEL_TITLE = {
    "full-tier": "Chess and knowledge tracing (nats per decision)",
    "opera-gpu": "OPeRA, user-profile LoRA and frozen prompt (nats per decision)",
    "sim2real-trio": "OPeRA, CoSER and HumanLike (nats per decision)",
    "osim-panel": "OPeRA, Osim (nats per decision)",
}


FAMILY_DISPLAY = {
    "static-embedding": "static embedding",
    "evolving-latent": "recurrent embedding",
    "structured-memory": "structured memory",
    "sft-lora": "user-profile LoRA",
    "persona-frozen": "frozen prompt",
    "strong-open": "frozen prompt (30B)",
    "trained-sim": "released simulator (Osim)",
    "sim2real-trio": "released simulator (Sim2Real)",
}
CONFIG_DISPLAY = {"chess-pooled": "chess", "kt-rt": "KT", "kt": "KT"}


def fam_disp(r):
    return FAMILY_DISPLAY.get(r["family"], r["family"])


def cfg_disp(r):
    c = r["config"]
    if r["family"] == "static-embedding" and c == "kt-rt" and r["channel"] == "move":
        return "KT (joint)"
    return CONFIG_DISPLAY.get(c, c)


def esc(s):
    return s.replace("_", "\\_").replace("|", "$\\mid$").replace("%", "\\%")


def fmt_v(x, nd=4):
    x = float(x)
    return f"{x:+.{nd}f}"


def channel_label(row):
    """The paper's name for the channel: the KT discrete channel is stored as "move"."""
    if row["channel"] == "move" and row["config"].startswith("kt"):
        return "response"
    return row["channel"]


def main():
    rows = list(csv.DictReader(open(SRC)))
    assert len(rows) == 84, len(rows)
    out = []
    out.append("% AUTO-GENERATED by attribution_trials.tables.master_ladder -- do not edit by hand")
    out.append("{\\scriptsize\\setlength{\\tabcolsep}{3pt}")
    out.append(
        "\\setlength{\\LTcapwidth}{\\linewidth}\\setlength{\\LTleft}{0pt}\\setlength{\\LTright}{0pt}\\begin{longtable}{@{\\extracolsep{\\fill}}llllr@{}}"
    )
    out.append(
        "\\caption{Target-versus-imposter gain $\\Delta_{\\mathrm{indiv}}$ for all 84 combinations, "
        "with its paired per-user bootstrap 95\\% interval; positive favors the target. "
        "A double dagger ($\\ddagger$) marks significance after Holm correction over the 84 combinations; "
        "a single dagger ($\\dagger$) marks significance only under the correction within each of these four groups of combinations. "
        "Both apply in either direction."
        "}\\label{tab:master-ladder}\\\\"
    )
    head = (
        "\\toprule\nfamily & channel & config & model & "
        "$\\Delta_{\\mathrm{indiv}}$ [95\\% CI] \\\\\n\\midrule"
    )
    out.append(head)
    out.append("\\endfirsthead")
    out.append("\\multicolumn{5}{@{}l}{\\emph{Table~\\thetable\\ (continued)}}\\\\\n" + head)
    out.append("\\endhead")
    out.append("\\bottomrule\\endlastfoot")
    for panel in PANEL_ORDER:
        prow = [r for r in rows if r["source"] == panel]
        out.append(
            f"\\multicolumn{{5}}{{@{{}}l}}{{\\textbf{{{PANEL_TITLE[panel]}}} "
            f"--- {len(prow)} combinations}}\\\\*\n\\midrule"
        )
        prow.sort(key=lambda r: (r["family"], channel_label(r), r["config"], r["model"]))
        for r in prow:
            # the CSV stores target-minus-imposter surprisal; the paper prints imposter minus target
            ci = (
                f"{fmt_v(-float(r['dindiv_point']))} [{fmt_v(-float(r['dindiv_high']))}, "
                f"{fmt_v(-float(r['dindiv_low']))}]"
            )
            if r["holm_reject_pooled_evidence"] == "True":
                ci += "$^{\\ddagger}$"
            elif r["holm_reject_within_source"] == "True":
                ci += "$^{\\dagger}$"
            out.append(
                " & ".join(
                    [
                        esc(fam_disp(r)),
                        esc(channel_label(r)),
                        esc(cfg_disp(r)) or "--",
                        esc(r["model"]) or "--",
                        ci,
                    ]
                )
                + " \\\\"
            )
        out.append("\\midrule")
    # drop the trailing midrule (bottomrule comes from endlastfoot)
    if out[-1] == "\\midrule":
        out.pop()
    out.append("\\end{longtable}")
    out.append("}")
    paths.ensure(OUT.parent)
    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
