"""Table: rules for choosing a WildChat simulator, scored against the content-gain ordering.

Reads ``selector_comparison.json`` (AT, profile versus no profile, absolute
similarity), ``frechet.json`` (population distance) and ``judge_readout.json``
(judged fidelity) under ``paths.WILDCHAT``; writes
``paths.TABLES / "selector_comparison.tex"``.

  python -m attribution_trials.tables.selector_comparison
"""

import json

from attribution_trials import paths

W = paths.WILDCHAT


def main():
    selector = {
        (r['selector'], r['endpoint']): r
        for r in json.loads((W / 'selector_comparison.json').read_text())['rows']
    }
    frechet = json.loads((W / 'frechet.json').read_text())
    judge = json.loads((W / 'judge_readout.json').read_text())
    for _k, _r in frechet['rows'].items():  # Frechet rows join on (selector, endpoint)
        _sel, _ep = _k.split(' | ')
        selector.setdefault((_sel, _ep), _r)
    assert judge['coverage']['n_missing'] == 0 and judge['coverage']['n_failed_in_judge'] == 0
    for _k, _r in judge['rows'].items():  # judge rows, same shape
        _sel, _ep = _k.split(' | ')
        selector.setdefault((_sel, _ep), _r)
    d_rows = [
        ("Profile versus no profile", "realusersim,userlm", 'profile vs no profile (-dtot)'),
        ("Absolute similarity, avg@8", "humanlm", 'absolute similarity, avg@8'),
        ("Absolute similarity, best@8", "humanlm", 'absolute similarity, best@8'),
        (
            "Population distribution distance",
            "distgap,simevalir",
            'population distance, Frechet (A4)',
        ),
        ("Judged fidelity", "realusersim,humanlm", 'judged fidelity (RealUserSim PT3 index)'),
        ("\\textbf{Attribution Trials} (ours)", None, 'AT (-dind)'),
    ]
    lines = [
        r"% AUTO-GENERATED by attribution_trials.tables.selector_comparison; do not edit by hand.",
        r"\begin{table}[t]",
        r"\definecolor{ATtablemuted}{HTML}{9AA1A8}",
        r"\caption{\textbf{Rules for choosing a simulator, scored against the content-gain ordering of "
        r"Table~\ref{tab:content-selection}.} Agree and $\tau$ as defined in Section~\ref{sec:downstream}. "
        r"Only the Attribution Trials row was "
        r"preregistered, and seven simulators do not separate the rows statistically.}",
        r"\label{tab:selector-comparison}",
        r"\centering",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{5pt}",
        r"\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}p{4.2cm}cccc@{}}",
        r"\toprule",
        r"& \multicolumn{2}{c}{avg@8} & \multicolumn{2}{c}{best@8} \\",
        r"\cmidrule(lr){2-3}\cmidrule(l){4-5}",
        r"Selection rule & Agree & $\tau$ & Agree & $\tau$ \\",
        r"\midrule",
    ]
    for name, cites, key in d_rows:
        head = (
            f"{name}\\newline\\citep{{{cites}}}" if cites else name
        )  # citation on its own line under the rule
        cells = []
        for ep in ('avg@8', 'best@8'):
            r = selector[(key, ep)]
            cells += [f"{r['n_agree']}/{r['n_resolvable']}", f"${r['kendall_tau']:+.2f}$"]
        if name.startswith("\\textbf"):
            lines.append(r"\midrule")
        lines.append(head + " & " + " & ".join(cells) + " \\\\")
    lines += [r"\bottomrule", r"\end{tabular*}", r"\end{table}"]
    out = paths.ensure(paths.TABLES) / 'selector_comparison.tex'
    out.write_text("\n".join(lines) + "\n")
    print("wrote", out)


if __name__ == '__main__':
    main()
