"""Appendix table: content gain at decoding temperature 1 and 0.7 for the three re-sampled simulators.

Reads ``paths.WILDCHAT / "temperature_readout.json"``; writes ``paths.TABLES / "temperature_check.tex"``.
Content gain = -(behavioral_delta_indiv); the change is the per-user paired difference, T=0.7 minus T=1.

  python -m attribution_trials.tables.temperature_check
"""

import json

from attribution_trials import paths

SRC = paths.WILDCHAT / "temperature_readout.json"
NAMES = {"8b": "Qwen3-8B", "humanlike": "HumanLike-7B", "osim": "Osim-8B"}


def main():
    g = json.loads(SRC.read_text())
    # The caption states the temperatures and that the ordering holds.
    assert g["baseline_temperature"] == 1.0 and g["rerun_temperature"] == 0.7
    assert all(g["three_way_ordering_holds"].values())
    lines = [
        "% AUTO-GENERATED by attribution_trials.tables.temperature_check; do not edit by hand.",
        r"\begin{table}[htbp]",
        r"\caption{\textbf{Decoding temperature does not change the selection result.} Content gain $\cgain$ of the three re-sampled simulators "
        r"at temperature 1 (the preregistered run) and 0.7, same 1{,}427 turns, profiles, and eight samples per condition; the change is the "
        r"per-user paired difference with its 95\% bootstrap interval. The ordering HumanLike-7B $>$ Qwen3-8B $>$ Osim-8B holds at both temperatures and both endpoints.}",
        r"\label{tab:temperature}",
        r"\centering",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{6pt}",
        r"\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}llrrr@{}}",
        r"\toprule",
        r"Simulator & Endpoint & $\cgain$ at $T{=}1$ & $\cgain$ at $T{=}0.7$ & Change [95\% CI] \\",
        r"\midrule",
    ]
    for cand in g["candidates"]:
        for ep in ("avg@8", "best@8"):
            base = -g["baseline"]["per_candidate"][cand][ep]["behavioral_delta_indiv"]["point"]
            new = -g["rerun"]["per_candidate"][cand][ep]["behavioral_delta_indiv"]["point"]
            ch = g["paired_change_in_content_gain_rerun_minus_baseline"][ep][cand]
            lo, hi = -ch["ci_high"], -ch["ci_low"]
            lines.append(
                f"{NAMES[cand]} & {ep} & ${base:+.3f}$ & ${new:+.3f}$ & ${-ch['point']:+.3f}$ [${lo:+.3f}$, ${hi:+.3f}$] \\\\"
            )
    lines += [r"\bottomrule", r"\end{tabular*}", r"\end{table}", ""]
    out = paths.ensure(paths.TABLES) / "temperature_check.tex"
    out.write_text("\n".join(lines))
    print("wrote", out)


if __name__ == "__main__":
    main()
